### ISSUE TITLE
Improve the verification scripts

### ISSUE THREAD

**Issue by lsaether** [w3f/kusama-genesis-spec#55]
What we're doing already is pulling the Ethereum state of the DOT Indicator Token and the Claims contract, then checking that the Substrate chain state matches. This works for the "important" stuff but it can't catch if there's some _extra_ erroneous storage. So what we want to do is basically iterate over all storage items in the script. There's a start of this already by checking the storage keys for the accounts, but we should do this with every storage item. It's probably easiest to query the raw storage keys directly and verify the values they point to.

I would describe the steps in this order:

- [ ] Sanity check the verification script as it's written.
- [ ] Pull all the storage keys from the new Substrate chain, even ones we "don't care about" (we want everything).
- [ ] Check there's no extra storage keys.
- [ ] Check values of the storage keys for correctness.

**Comment by ansonla3** [comment]
Checking the verification logic is done and the additional checking logics have been added in the recent [PRs](https://github.com/w3f/chainspec-generator/commit/5df4b57663ba2fb1b7ec3d2392098907918d7349). #60 #59 #56 #54
